name: Build website

on: [push]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      # 1/ Récupérer mes sources
      # 2/ Créer une archive de mon code source
      - name: récupération des sources (git clone)
        uses: actions/checkout@v3
      - name: Compression de mon site web
        run: tar cfz mon-site-web.tar.gz ./src/
      # 3/ Sauvegarder le résultat de ma commande précédente via un artefact
      - name: Sauvegarde de l'archive en tant qu'artefact
        users: actions/upload-artifact@v3
        with:
          name: website-source
          path: mon-site-web.tar.gz
